### ISSUE TITLE
cannot resolve 'app-path' during falcon-client build

### ISSUE THREAD

**Issue by nobuttsseb** [deity-io/falcon#110]
**Describe the bug**
When running the `falcon-client start` command for `falcon-client` the following error occurs during te build process:
```
ERROR in ./src/clientApp/index.js
Module not found: Error: Can't resolve 'app-path' in '/Users/_/Code/falcon/packages/falcon-client/src/clientApp'
 @ ./src/clientApp/index.js 1:0-32 3:15-26 4:32-54
 @ ./src/client.js
 @ multi /Users/_/Code/falcon/node_modules/razzle/config/polyfills.js /Users/_/Code/falcon/node_modules/razzle-dev-utils/webpackHotDevClient.js ./src/client

ERROR in ./src/i18n/i18nClientFactory.js
Module not found: Error: Can't resolve 'app-path/build/i18n' in '/Users/_/Code/falcon/packages/falcon-client/src/i18n'
 @ ./src/i18n/i18nClientFactory.js 5:9-86
 @ ./src/client.js
 @ multi /Users/_/Code/falcon/node_modules/razzle/config/polyfills.js /Users/_/Code/falcon/node_modules/razzle-dev-utils/webpackHotDevClient.js ./src/client

ERROR in ./src/client.js
```

**To Reproduce**
1. Run `node bin/falcon-client start`

**Expected behavior**
Build to complete without errors.

**Desktop (please complete the following information):**
 - OS: MAC 10.11.6

**Comment by Borales** [comment]
@nobuttsseb hi!
It looks like you're trying to start `falcon-client` package, is that so?

**Comment by nobuttsseb** [comment]
@Borales Correct!

**Comment by Borales** [comment]
@nobuttsseb you should try to start our example project (https://github.com/deity-io/falcon/tree/master/examples/shop-with-blog/client) that uses `falcon-client` package.

**Comment by nobuttsseb** [comment]
Thanks @Borales I got the example project working yesterday. I wanted to get `falcon-client` running independently in dev.

**Comment by Borales** [comment]
@nobuttsseb you want to run `falcon-client` for falcon-client development itself or start a new project using falcon-client?

**Comment by nobuttsseb** [comment]
I've just pulled and tried again and got this:

```
user:falcon-client sebastianwallace$ node bin/falcon-client start
Uncaught Exception:  { Error: Cannot find module 'webpack-virtual-modules'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/user/Code/falcon/packages/falcon-client/build-utils/webpack/config/create.js:12:30)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/user/Code/falcon/packages/falcon-client/build-utils/webpack/index.js:19:22)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32) code: 'MODULE_NOT_FOUND' }
```

**Comment by Borales** [comment]
@nobuttsseb you shouldn't be starting `falcon-client` itself, that's just a package. You need to start it within your project
