### ISSUE TITLE
Falcon Client : Cannot find module 'ajv/lib/compile/equal'

### ISSUE THREAD

**Issue by deity-bram** [deity-io/falcon#199]
**Describe the bug**
after a fresh in stall of falcon client i get a exception: Cannot find module 'ajv/lib/compile/equal'
when starting the app

**To Reproduce**
1 removing `/yarn.lock` file
2 running `yarn`
3 yarn start` in client example
4  problem 
**Expected behavior**
the falcon client starts

**Screenshots**
```
module.js:550
    throw err;
    ^
Error: Cannot find module 'ajv/lib/compile/equal'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/src/my-app/client/node_modules/webpackbar/node_modules/table/dist/validateConfig.js:2:13)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/src/my-app/client/node_modules/webpackbar/node_modules/table/dist/makeConfig.js:15:23)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
Error: The build failed because the process exited with code 1.
    at Object.runScript (/usr/src/my-app/client/node_modules/@deity/falcon-client/src/buildTools/razzle/index.js:23:11)
    at /usr/src/my-app/client/node_modules/@deity/falcon-client/bin/falcon-client.js:18:16
    at Object.<anonymous> (/usr/src/my-app/client/node_modules/@deity/falcon-client/bin/falcon-client.js:41:3)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Desktop (please complete the following information):**
On the server Linux apline 

**Additional context**

**Comment by deity-bram** [comment]
the core issue https://github.com/gajus/table/issues/83
temporary fix : add following lines to package.json an run npm install 

  "resolutions": {
    "ajv": "6.5.4"
  }
