### ISSUE TITLE
Error during rendering of /app-shell route in production mode (using nightly build)

### ISSUE THREAD

**Issue by mateuszwozniak** [deity-io/falcon#217]
**Describe the bug**
SSR server prints the following error when `yarn start:prod` is used:
```
Internal Server Error!
 request: /app-shell
 TypeError: Cannot read property 'httpLink' of undefined
    at new An (/Volumes/Data/workspace/deity/falcon/examples/shop-with-blog/client/build/server.js:127:164475)
    at /Volumes/Data/workspace/deity/falcon/examples/shop-with-blog/client/build/server.js:127:165628
    at w (/Volumes/Data/workspace/deity/falcon/examples/shop-with-blog/client/build/server.js:184:130398)
    at Generator._invoke (/Volumes/Data/workspace/deity/falcon/examples/shop-with-blog/client/build/server.js:184:130186)
    at Generator.e.(anonymous function) [as next] (/Volumes/Data/workspace/deity/falcon/examples/shop-with-blog/client/build/server.js:184:130577)
    at n (/Volumes/Data/workspace/deity/falcon/examples/shop-with-blog/client/build/server.js:15:35179)
    at s (/Volumes/Data/workspace/deity/falcon/examples/shop-with-blog/client/build/server.js:15:35389)
    at /Volumes/Data/workspace/deity/falcon/examples/shop-with-blog/client/build/server.js:15:35448
    at new Promise (<anonymous>)
    at /Volumes/Data/workspace/deity/falcon/examples/shop-with-blog/client/build/server.js:15:35330
```

**To Reproduce**
1. Start falcon server
2. Run `yarn build` in the client folder
3. Run `yarn start:prod` in the client folder
4. Open http://localhost:3000 in the browser
5. See the output on the console with running client

**Comment by tutok** [comment]
it is not necessary to build a production package, it also happens in dev mode when accessing `http://localhost:3000/app-shell` url.

**Comment by cane-lagerwaard** [comment]
> it is not necessary to build a production package, it also happens in dev mode when accessing `http://localhost:3000/app-shell` url.

Can confirm
