### ISSUE TITLE
`/app-shell ` throws 500

### ISSUE THREAD

**Issue by tutok** [deity-io/falcon#218]
**Describe the bug**
app shell page is not returned, 500 instead

**To Reproduce**
1. Go to `/app-shell`
```
Internal Server Error!
 request: /app-shell
 TypeError: Cannot read property 'httpLink' of undefined
    at new ApolloClient (C:\A\Deity\falcon\examples\shop-with-blog\client\build\webpack:\C:\A\Deity\falcon\packages\falcon-client\src\service\ApolloClient.js:28:1)
    at _callee$ (C:\A\Deity\falcon\examples\shop-with-blog\client\build\webpack:\C:\A\Deity\falcon\packages\falcon-client\src\middlewares\routes\apolloClientProvider.js:56:1)
    at tryCatch (C:\A\Deity\falcon\examples\shop-with-blog\client\build\webpack:\C:\A\Deity\falcon\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:62:1)
    at Generator.invoke [as _invoke] (C:\A\Deity\falcon\examples\shop-with-blog\client\build\webpack:\C:\A\Deity\falcon\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:288:1)
    at Generator.prototype.(anonymous function) [as next] (C:\A\Deity\falcon\examples\shop-with-blog\client\build\webpack:\C:\A\Deity\falcon\node_modules\@babel\runtime\node_modules\regenerator-runtime\runtime.js:114:1)
    at asyncGeneratorStep (C:\A\Deity\falcon\examples\shop-with-blog\client\build\webpack:\C:\A\Deity\falcon\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:1)
    at _next (C:\A\Deity\falcon\examples\shop-with-blog\client\build\webpack:\C:\A\Deity\falcon\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:1)
    at C:\A\Deity\falcon\examples\shop-with-blog\client\build\webpack:\C:\A\Deity\falcon\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:1
    at new Promise (<anonymous>)
    at C:\A\Deity\falcon\examples\shop-with-blog\client\build\webpack:\C:\A\Deity\falcon\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:
```

**Expected behavior**
app shell html page should be returned

**Screenshots**

**Comment by tutok** [comment]
related #217
