### ISSUE TITLE
Falcon-server fails to obtain Magento admin token

### ISSUE THREAD

**Issue by Borales** [deity-io/falcon#228]
**Describe the bug**

```
2018-12-11 02:14:25:184] debug: api-magento2: POST http://localhost/m2/rest/default/V1/integration/admin/token (49ms)
[2018-12-11 02:14:25:184] error: FalconServer: undefined
[2018-12-11 02:14:25:185] error: FalconServer: Initialization error - cannot start the server
[2018-12-11 02:14:25:185] error: Error
   at Magento2Api.<anonymous> (/home/pcis/my-app/server/node_modules/apollo-datasource-rest/dist/RESTDataSource.js:77:25)
   at Generator.next (<anonymous>)
   at /home/pcis/my-app/server/node_modules/apollo-datasource-rest/dist/RESTDataSource.js:7:71
   at new Promise (<anonymous>)
   at __awaiter (/home/pcis/my-app/server/node_modules/apollo-datasource-rest/dist/RESTDataSource.js:3:12)
   at Magento2Api.errorFromResponse (/home/pcis/my-app/server/node_modules/apollo-datasource-rest/dist/RESTDataSource.js:67:16)
   at Magento2Api.<anonymous> (/home/pcis/my-app/server/node_modules/apollo-datasource-rest/dist/RESTDataSource.js:50:34)
   at Generator.next (<anonymous>)
   at /home/pcis/my-app/server/node_modules/apollo-datasource-rest/dist/RESTDataSource.js:7:71
   at new Promise (<anonymous>)
```

**To Reproduce**
1. Install nightly version
2. Install Magento Module
3. Start Falcon-server

**Desktop (please complete the following information):**
- Ubuntu 16.04
- php version 7.1.24
- Apache2
- Magento 2.2.6 in web directory /var/www/html/m2
- Falcon in /home/pcis/my-app/

**Additional context**
Magento config

```
"config": {
  "host": "localhost/m2",
  "protocol": "http",
  "username": "deity",
  "password": "deity123"
}
```

**Comment by Borales** [comment]
Outdated Magento cache was the problem, closing this issue
