### ISSUE TITLE
Example project should work also if the connect Magento has no category with id: 25

### ISSUE THREAD

**Issue by borriglione** [deity-io/falcon#291]
In `./examples/shop-with-blog/client/src/pages/Home.js`:

```
    <Query query={HOMEPAGE_PRODUCTS_QUERY} variables={{ categoryId: '25', amount: 20 }}>
      {({ category }) => <ProductsList products={category.products.items} />}
    </Query>
```

categoryId: '25' is required as category in Magento. This works of course only if the connected Magento has a category with id: 25. Otherwise the app fails with error:

```
{ message: 'Keine Eintrag mit id = 25',
  locations: [ { line: 2, column: 3 } ],
  path: [ 'category' ],
  extensions: { code: 'NOT_FOUND' } }
Internal Server Error!
 request: /
 { GraphQL error: Keine Eintrag mit id = 25
    at new ApolloError (amla-deity/client/node_modules/src/errors/ApolloError.ts:56:5)
    at amla-deity/client/node_modules/src/core/QueryManager.ts:515:31
    at amla-deity/client/node_modules/src/core/QueryManager.ts:1036:11
    at Array.forEach (<anonymous>)
    at amla-deity/client/node_modules/src/core/QueryManager.ts:1035:10
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (amla-deity/client/node_modules/src/core/QueryManager.ts:1029:18)
    at Object.next (amla-deity/client/node_modules/src/core/QueryManager.ts:1130:18)
    at notifySubscription (amla-deity/client/node_modules/zen-observable/lib/Observable.js:130:18)
    at onNotify (amla-deity/client/node_modules/zen-observable/lib/Observable.js:165:3)
  graphQLErrors:
   [ { message: 'Keine Eintrag mit id = 25',
       locations: [Array],
       path: [Array],
       extensions: [Object] } ],
  networkError: null,
  message: 'GraphQL error: Keine Eintrag mit id = 25',
  extraInfo: undefined }
```

Would be great to remove this requirement to improve first development steps with Falcon.

**Comment by cane-lagerwaard** [comment]
@borriglione thanks for your feedback. We'll look into the issue
