### ISSUE TITLE
'npm start' on client throws error in create-falcon-app

### ISSUE THREAD

**Issue by Piorys** [deity-io/falcon#34]
**Describe the bug**
Upon starting the client terminal session via "npm start" using create-falcon-app, error messages are appearing hanging the execution of the script.

**To Reproduce**
1. Clone Falcon via git clone
2. Hit "npm install"
3. Hit "npx create-falcon-app my-app"
4. cd into my-app/client
5. hit npm start

**Expected behavior**
Client session should start, creating the project

**Terminal Log**
```
npm start

> @deity/example-shop-with-blog-client@1.0.0 start /Users/****/Desktop/Różne/projekty/falcon/my-app/client
> falcon-client start

 WAIT  Compiling...

Using .eslintrc defined in your app root
Using .eslintrc defined in your app root
Starting type checking service...
Using 1 worker with 2048MB memory limit
Watching: /Users/******/Desktop/Różne/projekty/falcon/my-app/client/src
✔ success client compiled in 5s 540ms
No type errors found
Version: typescript 3.1.1
Time: 3380ms

Compiling

● client

● server █████████████████████████ compiling (0%)


✖ ｢wdm｣: Hash: 8cfe01f0d92cfab5360e
Version: webpack 4.20.2
Time: 5554ms
Built at: 2018-10-04 13:33:12
                                Asset       Size          Chunks             Chunk Names
      static/js/shop/product.chunk.js   2.31 KiB    shop/product  [emitted]  shop/product
       static/media/logo.567bab07.png   5.13 KiB                  [emitted]
 static/manifest.ae5fb222.webmanifest   1.31 KiB                  [emitted]
                  static/js/client.js   1.42 MiB          client  [emitted]  client
    static/js/i18n/en-common.chunk.js  293 bytes  i18n/en-common  [emitted]  i18n/en-common
      static/js/i18n/en-post.chunk.js  241 bytes    i18n/en-post  [emitted]  i18n/en-post
      static/js/i18n/en-shop.chunk.js  757 bytes    i18n/en-shop  [emitted]  i18n/en-shop
     static/js/shop/category.chunk.js   2.33 KiB   shop/category  [emitted]  shop/category
       static/media/logo.377581b7.svg   8.11 KiB                  [emitted]
           static/js/vendors.chunk.js   2.05 MiB         vendors  [emitted]  vendors
              static/js/client.js.map   1.43 MiB          client  [emitted]  client
static/js/i18n/en-common.chunk.js.map  109 bytes  i18n/en-common  [emitted]  i18n/en-common
  static/js/i18n/en-post.chunk.js.map  107 bytes    i18n/en-post  [emitted]  i18n/en-post
  static/js/i18n/en-shop.chunk.js.map  107 bytes    i18n/en-shop  [emitted]  i18n/en-shop
 static/js/shop/category.chunk.js.map  773 bytes   shop/category  [emitted]  shop/category
  static/js/shop/product.chunk.js.map  749 bytes    shop/product  [emitted]  shop/product
       static/js/vendors.chunk.js.map   2.05 MiB         vendors  [emitted]  vendors
Entrypoint client = static/js/vendors.chunk.js static/js/vendors.chunk.js.map static/js/client.js static/js/client.js.map
[./node_modules/@deity/falcon-client/src/client.js] 2.83 KiB {client} [built]
[./node_modules/@deity/falcon-client/src/clientApp/index.js] 55 bytes {client} [built]
[./node_modules/@deity/falcon-client/src/components/HtmlHead.js] 552 bytes {client} [built]
[./node_modules/@deity/falcon-client/src/graphql/config.gql] 206 bytes {client} [built] [failed] [1 error]
[./node_modules/@deity/falcon-client/src/i18n/i18nClientFactory.js] 1.81 KiB {client} [built]
[./node_modules/@deity/falcon-client/src/service/ApolloClient.js] 2.67 KiB {client} [built]
[./node_modules/@deity/falcon-client/src/serviceWorker/index.js] 1.33 KiB {client} [built]
[./node_modules/object-assign/index.js] 2.06 KiB {client} [built]
[./node_modules/razzle-dev-utils/webpackHotDevClient.js] 7.56 KiB {client} [built]
[./node_modules/razzle/config/polyfills.js] 1.06 KiB {vendors} [built]
[./node_modules/react/index.js] 190 bytes {vendors} [built]
[./node_modules/sockjs-client/lib/entry.js] 244 bytes {client} [built]
[./node_modules/strip-ansi/index.js] 161 bytes {client} [built]
[./src/manifest.webmanifest] 82 bytes {client} [built]
[0] multi ./node_modules/razzle/config/polyfills.js ./node_modules/razzle-dev-utils/webpackHotDevClient.js ./node_modules/@deity/falcon-client/src/client.js 52 bytes {client} [built]
    + 675 hidden modules

ERROR in ./node_modules/@deity/falcon-client/src/graphql/config.gql 1:6
Module parse failed: Unexpected token (1:6)
You may need an appropriate loader to handle this file type.
> query CLIENT_SIDE_APP_INIT {
|   config @client {
|     serverSideRendering
 @ ./node_modules/@deity/falcon-client/src/client.js 13:0-60 25:50-70
 @ multi ./node_modules/razzle/config/polyfills.js ./node_modules/razzle-dev-utils/webpackHotDevClient.js ./node_modules/@deity/falcon-client/src/client.js

ERROR in ./node_modules/@deity/falcon-client/src/graphql/url.gql 1:6
Module parse failed: Unexpected token (1:6)
You may need an appropriate loader to handle this file type.
> query GET_URL($path: String!) {
✔ success client compiled in 149ms
Type checking in progress...
✖ ｢wdm｣: Hash: 8cfe01f0d92cfab5360e
Version: webpack 4.20.2
Time: 150ms
Built at: 2018-10-04 13:33:13
                                Asset       Size          Chunks             Chunk Names
      static/js/shop/product.chunk.js   2.31 KiB    shop/product             shop/product
       static/media/logo.567bab07.png   5.13 KiB
 static/manifest.ae5fb222.webmanifest   1.31 KiB
                  static/js/client.js   1.42 MiB          client             client
    static/js/i18n/en-common.chunk.js  293 bytes  i18n/en-common             i18n/en-common
      static/js/i18n/en-post.chunk.js  241 bytes    i18n/en-post             i18n/en-post
      static/js/i18n/en-shop.chunk.js  757 bytes    i18n/en-shop             i18n/en-shop
     static/js/shop/category.chunk.js   2.33 KiB   shop/category             shop/category
       static/media/logo.377581b7.svg   8.11 KiB                  [emitted]
           static/js/vendors.chunk.js   2.05 MiB         vendors             vendors
              static/js/client.js.map   1.43 MiB          client             client
static/js/i18n/en-common.chunk.js.map  109 bytes  i18n/en-common             i18n/en-common
  static/js/i18n/en-post.chunk.js.map  107 bytes    i18n/en-post             i18n/en-post
  static/js/i18n/en-shop.chunk.js.map  107 bytes    i18n/en-shop             i18n/en-shop
 static/js/shop/category.chunk.js.map  773 bytes   shop/category             shop/category
  static/js/shop/product.chunk.js.map  749 bytes    shop/product             shop/product
       static/js/vendors.chunk.js.map   2.05 MiB         vendors             vendors
Entrypoint client = static/js/vendors.chunk.js static/js/vendors.chunk.js.map static/js/client.js static/js/client.js.map
[./node_modules/@deity/falcon-client/src/client.js] 2.83 KiB {client}
[./node_modules/@deity/falcon-client/src/clientApp/index.js] 55 bytes {client}
[./node_modules/@deity/falcon-client/src/components/HtmlHead.js] 552 bytes {client}
[./node_modules/@deity/falcon-client/src/graphql/config.gql] 206 bytes {client} [built] [failed] [1 error]
[./node_modules/@deity/falcon-client/src/i18n/i18nClientFactory.js] 1.81 KiB {client}
[./node_modules/@deity/falcon-client/src/service/ApolloClient.js] 2.67 KiB {client}
[./node_modules/@deity/falcon-client/src/serviceWorker/index.js] 1.33 KiB {client}
[./node_modules/object-assign/index.js] 2.06 KiB {client}
[./node_modules/razzle-dev-utils/webpackHotDevClient.js] 7.56 KiB {client}
[./node_modules/razzle/config/polyfills.js] 1.06 KiB {vendors}
[./node_modules/react/index.js] 190 bytes {vendors}
[./node_modules/sockjs-client/lib/entry.js] 244 bytes {client}
[./node_modules/strip-ansi/index.js] 161 bytes {client}
[./src/manifest.webmanifest] 82 bytes {client}
[0] multi ./node_modules/razzle/config/polyfills.js ./node_modules/razzle-dev-utils/webpackHotDevClient.js ./node_modules/@deity/falcon-client/src/client.js 52 bytes {client}
    + 675 hidden modules

ERROR in ./node_modules/@deity/falcon-client/src/graphql/config.gql 1:6
Module parse failed: Unexpected token (1:6)
You may need an appropriate loader to handle this file type.
> query CLIENT_SIDE_APP_INIT {
|   config @client {
|     serverSideRendering
 @ ./node_modules/@deity/falcon-client/src/client.js 13:0-60 25:50-70
 @ multi ./node_modules/razzle/config/polyfills.js ./node_modules/razzle-dev-utils/webpackHotDevClient.js ./node_modules/@deity/falcon-client/src/client.js

ERROR in ./node_modules/@deity/falcon-client/src/graphql/url.gql 1:6
Module parse failed: Unexpected token (1:6)
You may need an appropriate loader to handle this file type.
> query GET_URL($path: String!) {
|   url(path: $path) {
|     type
 @ ./node_modules/@deity/falcon-client/src/components/DynamicRoute.js 6:0-47 20:13-20
 @ ./src/App.js
 @ ./index.js
 @ ./node_modules/@deity/falcon-client/src/clientApp/index.js
 @ ./node_modules/@deity/falcon-client/src/client.js
 @ multi ./node_modules/razzle/config/polyfills.js ./node_modules/razzle-dev-utils/webpackHotDevClient.js ./node_modules/@deity/falcon-client/src/client.js
✔ success server compiled in 1s 39ms

/Users/******/Desktop/Różne/projekty/falcon/my-app/client/build/server.js:1300
throw new Error("Module parse failed: Unexpected token (1:6)\nYou may need an appropriate loader to handle this file type.\n> query CLIENT_SIDE_APP_INIT {\n|   config @client {\n|     serverSideRendering");
      ^
Module parse failed: Unexpected token (1:6)
You may need an appropriate loader to handle this file type.
> query CLIENT_SIDE_APP_INIT {
|   config @client {
|     serverSideRendering
    at Object../node_modules/@deity/falcon-client/src/graphql/config.gql (/Users/******/Desktop/Różne/projekty/falcon/my-app/client/build/server.js:1300:7)
    at __webpack_require__ (/Users/******/Desktop/Różne/projekty/falcon/my-app/client/webpack/bootstrap:688:1)
    at fn (/Users/******/Desktop/Różne/projekty/falcon/my-app/client/build/webpack:/webpack/bootstrap:59:1)
    at Module../node_modules/@deity/falcon-client/src/middlewares/routes/helmetMiddleware.js (/Users/******/Desktop/Różne/projekty/falcon/my-app/client/build/server.js:1805:77)
    at __webpack_require__ (/Users/******/Desktop/Różne/projekty/falcon/my-app/client/build/webpack:/webpack/bootstrap:688:1)
    at fn (/Users/******/Desktop/Różne/projekty/falcon/my-app/client/build/webpack:/webpack/bootstrap:59:1)
    at Module../node_modules/@deity/falcon-client/src/middlewares/routes/index.js (/Users/******/Desktop/Różne/projekty/falcon/my-app/client/build/server.js:1953:75)
    at __webpack_require__ (/Users/******/Desktop/Różne/projekty/falcon/my-app/client/build/webpack:/webpack/bootstrap:688:1)
    at fn (/Users/******/Desktop/Różne/projekty/falcon/my-app/client/build/webpack:/webpack/bootstrap:59:1)
    at Module../node_modules/@deity/falcon-client/src/server.js (/Users/******/Desktop/Różne/projekty/falcon/my-app/client/build/server.js:2441:77)
No type errors found
Version: typescript 3.1.1
Time: 966ms
```

**Desktop (please complete the following information):**
 - MacOS High Sierra
-  Node.JS v8.11.3

**Additional context**
NOTE: On the other hand server terminal session runs ok. Alas upon entering the site I'm getting "Not Found"

**Comment by cane-lagerwaard** [comment]
Thank you for mentioning. We are currently looking into it.

**Comment by cane-lagerwaard** [comment]
@Piorys Issue should be fixed. Please try running ```npx create-falcon-app my-app``` again

**Comment by Piorys** [comment]
@cane-lagerwaard Thanks for the info
I have performed the restest, and the 'npm start' scripts finished successfully.  

Although there may be another minor issue, that right after "Started" terminal log, error shows:

```
Internal Server Error!
 request: /_next/webpack-hmr
 { FetchError: request to http://localhost:4000/graphql failed, reason: connect ECONNREFUSED 127.0.0.1:4000
    at ClientRequest.<anonymous> (/Users/*******/Desktop/Różne/projekty/falcon/my-app/client/node_modules/node-fetch/lib/index.js:1345:11)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at Socket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  message: 'request to http://localhost:4000/graphql failed, reason: connect ECONNREFUSED 127.0.0.1:4000',
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED' }
```

**Comment by Piorys** [comment]
@Borales Actually aforementioned error shows 2 times. First time right after running the client app, before the server, and the second time during starting the server app.

**Comment by Borales** [comment]
@Piorys hi, could you please check this problem one more time with the latest packages?

**Comment by cane-lagerwaard** [comment]
Errors are no longer present, bug should be fixed. Therefore closing this issue. Thanks @Piorys for your help
