### ISSUE TITLE
Error: Cannot find module '@deity/eslint-config-falcon'

### ISSUE THREAD

**Issue by chetabahana** [deity-io/falcon#343]
**Failed during falcon/my-app/client**
command
```
cd /home/chetabahana/falcon/my-app/client
npm run start
``
Output
````
Module build failed (from ./node_modules/eslint-loader/index.js):
Error: Cannot find module '@deity/eslint-config-falcon'

  1 | // eslint-disable-next-line import/no-extraneous-dependencies
> 2 | const esLint = require('@deity/eslint-config-falcon');
  3 | 
  4 | module.exports = Object.assign({}, esLint.rules['prettier/prettier'][1], {
  5 |   overrides: [

at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/chetabahana/falcon/prettier.config.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```
**Meanwhile run falcon/my-app/server is OK**
command
```
cd /home/chetabahana/falcon/my-app/server
npm run start
```
Output
```
> @deity/example-shop-with-blog-server@0.3.0 start /home/chetabahana/falcon/my-app/server
> cross-env NODE_ENV=development nodemon index.js

[nodemon] 1.18.10
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node index.js`
[2019-03-13 03:39:35:614] info: Starting Falcon Server
[2019-03-13 03:39:36:192] info: 🚀 Server ready at http://localhost:4000
[2019-03-13 03:39:36:193] info: 🌍 GraphQL endpoint ready at http://localhost:4000/graphql

```

**Comment by Borales** [comment]
@chetabahana Hi. I just did a quick check with `npx create-falcon-app my-app` and I managed to run the `client` app. Please make sure your dependencies were installed properly (the easiest way is to remove your `client/node_modules` folder and install your dependencies once again).

**Comment by chetabahana** [comment]
@Borales Hi, thanks for your advise. I have deleted `client/node_modules` but same error

```
Step #1: Module build failed (from ./node_modules/eslint-loader/index.js):
Step #1: Error: Cannot find module '@deity/eslint-config-falcon'
Step #1: 
Step #1: 1 | // eslint-disable-next-line import/no-extraneous-dependencies
Step #1: > 2 | const esLint = require('@deity/eslint-config-falcon');
Step #1: 3 | 
```

Here is the full [build.log](https://github.com/deity-io/falcon/files/2974639/build.log)

**Comment by cane-lagerwaard** [comment]
Hi @chetabahana could you provide system information and node version?

**Comment by huya03487** [comment]
I got the same . Anyone can help ?

**Comment by Borales** [comment]
@huya03487 @chetabahana hi guys, could you please check again if this issue is still relevant?
