### ISSUE TITLE
How to run dev server?

### ISSUE THREAD

**Issue by mickidum** [deity-io/falcon#350]
Follow from docs

1. npx create-falcon-app myapp
2. cd my-app/server
    npm start // works as expected
3. cd my-app/client
    npm start // works as expected
4. navigating to http://localhost:3000
    getting error
`/var/www/falcon/my-app/client/node_modules/zen-observable/lib/Observable.js:90
      cleanup();
      ^
TypeError: Cannot read property 'delete' of undefined
    at /var/www/falcon/my-app/client/node_modules/apollo-link-dedup/src/dedupLink.ts:66:36
    at cleanupSubscription (/var/www/falcon/my-app/client/node_modules/zen-observable/lib/Observable.js:90:7)
    at notifySubscription (/var/www/falcon/my-app/client/node_modules/zen-observable/lib/Observable.js:145:41)
    at onNotify (/var/www/falcon/my-app/client/node_modules/zen-observable/lib/Observable.js:165:3)
    at SubscriptionObserver.error (/var/www/falcon/my-app/client/node_modules/zen-observable/lib/Observable.js:224:7)
    at /var/www/falcon/my-app/client/node_modules/apollo-link-dedup/src/dedupLink.ts:59:48
    at Set.forEach (<anonymous>)
    at Object.error (/var/www/falcon/my-app/client/node_modules/apollo-link-dedup/src/dedupLink.ts:59:29)
    at notifySubscription (/var/www/falcon/my-app/client/node_modules/zen-observable/lib/Observable.js:134:18)
    at onNotify (/var/www/falcon/my-app/client/node_modules/zen-observable/lib/Observable.js:165:3)`

What I am missing?
Thank you.

**Comment by mateuszwozniak** [comment]
Hi @mickidum. This issue popped out today with the latest updates from Apollo team, it's related to [this problem](https://github.com/apollographql/apollo-link/issues/986). Apollo team is working on a quick fix but in the meantime, you can do the following:
1. Open `client/package.json` file and add the following code before last `}`:
```
  "resolutions": {
    "apollo-link-dedup": "1.0.15"
  }
```
2. Remove `client/yarn.lock` (if you have it there) and `client/node_modules`
3. Run `yarn install` in `client` folder (NOTE: it needs to be `yarn` not `npm` because `npm` doesn't use `resolutions`.

That will tell yarn to install version `1.0.15` of `apollo-link-dedup` which works correctly.
After those steps, client dev server should start without problems.

**Comment by mickidum** [comment]
Works. Thank you

**Comment by mateuszwozniak** [comment]
Apollo team has already released bugfix, so that shouldn't happen anymore :)
