### ISSUE TITLE
falcon-scripts requires "graphql-tag" to be installed

### ISSUE THREAD

**Issue by Borales** [deity-io/falcon#648]
**Describe the bug**
In order to use `falcon-scripts` to build a TS-based package - it's required to have `graphql-tag` package installed (even though it's not being used).

**To Reproduce**
1. Create a generic TS project (with a simple `src/index.ts`)
2. Run `falcon-scripts build`
3. See error:

```
Error: Cannot find module 'graphql-tag'
Require stack:
- [redacted]/node_modules/babel-plugin-graphql-tag/dist/index.js
- [redacted]/node_modules/@babel/core/lib/config/files/plugins.js
- [redacted]/node_modules/@babel/core/lib/config/files/index.js
- [redacted]/node_modules/@babel/core/lib/index.js
- [redacted]/node_modules/@babel/cli/lib/babel/options.js
- [redacted]/node_modules/@babel/cli/lib/babel/index.js
- [redacted]/node_modules/@babel/cli/bin/babel.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> ([redacted]/node_modules/babel-plugin-graphql-tag/dist/index.js:16:42)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '[redacted]/node_modules/babel-plugin-graphql-tag/dist/index.js',
    '[redacted]/node_modules/@babel/core/lib/config/files/plugins.js',
    '[redacted]/node_modules/@babel/core/lib/config/files/index.js',
    '[redacted]/node_modules/@babel/core/lib/index.js',
    '[redacted]/node_modules/@babel/cli/lib/babel/options.js',
    '[redacted]/node_modules/@babel/cli/lib/babel/index.js',
    '[redacted]/node_modules/@babel/cli/bin/babel.js'
  ]
}
{
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 37379,
  stdout: null,
  stderr: null,
  error: null
}
```

**Comment by tutok** [comment]
because of this https://github.com/deity-io/falcon/blob/cc2d211f8da4c7826d8ebcb2614e0cd11754f5e8/packages/falcon-dev-tools/falcon-scripts/src/babel/babel.config.js#L25-L25
so we need to add it to dependencies list

**Comment by Borales** [comment]
@tutok can we make it optional?

**Comment by tutok** [comment]
yeah, actually scanning package dependencies to search `graphql-tag` is a good idea!
