### ISSUE TITLE
GraphQL error: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by tutok** [deity-io/falcon#734]
**Describe the bug**
`ERROR: Cannot read property 'match' of undefined`

full stack trace:
```
@deity/example-shop-with-blog-server: [2019-11-27 10:04:37.772] ERROR: Cannot read property 'match' of undefined
@deity/example-shop-with-blog-server: GraphQL Error Code: INTERNAL_SERVER_ERROR
@deity/example-shop-with-blog-server: Path: category.productList
@deity/example-shop-with-blog-server: File: C:\A\Deity\falcon\packages\falcon-magento2-api\src\index.ts
@deity/example-shop-with-blog-server: ------------------------------------------------------------------------------------------------------------------------------
@deity/example-shop-with-blog-server:  199 |         { context: { pagination } }
@deity/example-shop-with-blog-server:  200 |       );
@deity/example-shop-with-blog-server:  201 |     } catch (ex) {
@deity/example-shop-with-blog-server:  202 |       // if is_anchor is set to "0" then we cannot fetch category contents (as it doesn't have products)
@deity/example-shop-with-blog-server:  203 |       // in that case if Magento returns error "Bucked does not exist" we return empty array to avoid displaying errors
@deity/example-shop-with-blog-server:  204 |       if (ex.message.match(/Bucket does not exist/) && obj.custom_attributes.is_anchor === '0') {
@deity/example-shop-with-blog-server:  205 |         return {
@deity/example-shop-with-blog-server:  206 |           items: [],
@deity/example-shop-with-blog-server:  207 |           pagination: this.processPagination(0)
@deity/example-shop-with-blog-server:  208 |         };
@deity/example-shop-with-blog-server:  209 |       }
@deity/example-shop-with-blog-server: ------------------------------------------------------------------------------------------------------------------------------
@deity/example-shop-with-blog-server:     TypeError: Cannot read property 'match' of undefined
@deity/example-shop-with-blog-server:         at Magento2Api.match [as categoryProductList] (C:\A\Deity\falcon\packages\falcon-magento2-api\src\index.ts:204:22)
@deity/example-shop-with-blog-server:         at processTicksAndRejections (internal/process/task_queues.js:85:5)
```
**To Reproduce**
1. `yarn start`
2. played with app, full page reload, navigating, introduced some changes to check HMR, 

additional context:
for sure I visited `/sale` category page (I think it could be connected) 

**Expected behavior**
receive a page for requested URL

**Screenshots**
page does not load at all

**Comment by tutok** [comment]
when I was turned off SSR I can see:

![image](https://user-images.githubusercontent.com/1831641/69710438-b229a500-10ff-11ea-9c17-410e1814f85f.png)

so it looks like there is a problem also on falcon client. He can not handle errors on the server-side correctly.
